apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  namespace: argocd
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/argo"
        backend:
          service:
            name: example-service
            port:
              number: 80
