apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  type: LoadBalancer
  namespace: example-app
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000