apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    type: LoadBalancer
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000